<font size="8"> N numpy exercises
<font>


1. Import the numpy package under the name np (★☆☆)

In [86]:
import numpy as np
from numpy.linalg import matrix_rank

2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

2.3.5


3. Create a null vector of size 10 (★☆☆)

ceros = np.zeros(10)
print(ceros)

4. How to find the memory size of any array (★☆☆)

In [11]:
print(ceros.nbytes)

80


7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [18]:
values_1 = np.arange(10,49)
print(values_1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


8. Reverse a vector (first element becomes last) (★☆☆)

In [22]:
reverse_vec = np.flip(values_1)
print(reverse_vec)


[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [25]:
m=np.arange(0,9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [27]:
vec1=np.array([1,2,0,0,4,0])
print(np.nonzero(vec1))

(array([0, 1, 4]),)


In [ ]:
11. Create a 3x3 identity matrix (★☆☆)

In [28]:
vec2=np.identity(3)
print(vec2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values (★☆☆)

In [29]:
m2=np.random.random((3, 3, 3))
print(m2)

[[[0.48466034 0.61891027 0.84635638]
  [0.85228453 0.06668104 0.31157904]
  [0.52001433 0.53501433 0.99892972]]

 [[0.31610051 0.24232246 0.63577534]
  [0.07992655 0.70909854 0.81428691]
  [0.05811765 0.97339486 0.29330123]]

 [[0.87611138 0.63322397 0.47255299]
  [0.63523784 0.72446109 0.62330333]
  [0.24662145 0.00824837 0.2707291 ]]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [33]:
m3=np.random.random((10,10))
print(m3)
print("The maximum value in the arrray is " + str(np.max(m3)))
print("The minimum value in the arrray is " + str(np.min(m3)))

[[0.00950322 0.66500649 0.48829375 0.11685927 0.66186781 0.99289337
  0.71908846 0.08143932 0.22592792 0.17074869]
 [0.70127625 0.78519545 0.83062907 0.26823383 0.07036269 0.78752151
  0.22537107 0.52303384 0.46443291 0.2382053 ]
 [0.25495314 0.37182728 0.52270076 0.75994144 0.46444337 0.99716695
  0.52837722 0.43269151 0.64305127 0.17080462]
 [0.27489223 0.06703681 0.88091442 0.9179484  0.02528387 0.79515889
  0.49919288 0.84889579 0.47600692 0.51999737]
 [0.2596766  0.08885977 0.45973303 0.44920348 0.28759319 0.35200593
  0.2150206  0.83561129 0.04983334 0.41447173]
 [0.63931377 0.59338674 0.06123886 0.64751202 0.17908527 0.29706774
  0.31676538 0.01912721 0.08496029 0.01971906]
 [0.74477118 0.06761458 0.66916068 0.10373012 0.27117117 0.00530981
  0.20326144 0.9989434  0.40388254 0.62865139]
 [0.54418459 0.26563417 0.66033092 0.69780023 0.16102871 0.00178881
  0.0882729  0.56222978 0.51628858 0.56776465]
 [0.53684364 0.09669086 0.95330746 0.44190521 0.95414455 0.77852751
  0.42201423

37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [36]:
m4 = np.zeros((5, 5))
m4 += np.arange(5)
print(m4)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [38]:
vec2=np.full(10,np.arange(0,1))
print(vec2)

[0 0 0 0 0 0 0 0 0 0]


In [39]:
vec3 = np.linspace(0, 1, 12, endpoint=True)[1:-1]

print(vec3)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it (★★☆)

In [45]:
vec4 = np.random.random(10)
print(vec4)
vec4.sort()
print(vec4)

[0.80374131 0.71674489 0.53328459 0.0599786  0.27627683 0.58523001
 0.80479981 0.1371263  0.18896157 0.93479869]
[0.0599786  0.1371263  0.18896157 0.27627683 0.53328459 0.58523001
 0.71674489 0.80374131 0.80479981 0.93479869]


42. Consider two random arrays A and B, check if they are equal (★★☆)

In [49]:
vec5 = np.random.random(11)
vec6 = np.random.random(11)
print(vec5)
print(vec6)
### two ways to compare
print(vec5 == vec6)
are_equal = np.array_equal(vec5, vec6)
print(are_equal) 

[0.56004055 0.62517574 0.18506395 0.87447668 0.37182506 0.36551105
 0.14586575 0.52998488 0.79971215 0.75926131 0.52803786]
[0.60254353 0.76018427 0.18997152 0.51298985 0.38351749 0.80354429
 0.26051915 0.44249149 0.60741869 0.32871715 0.52217877]
[False False False False False False False False False False False]
False


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

In [55]:
n = 2
area = np.zeros((n, n), [('x', float), ('y', float)])
grid_values = np.linspace(0, 1, n)
area['x'], Z['y'] = np.meshgrid(grid_values, grid_values)

print(area)

[[(0., 0.) (1., 0.)]
 [(0., 0.) (1., 0.)]]


48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [54]:
# Integer types
for dtype in [np.int8, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: min = {info.min}, max = {info.max}")

print("-" * 30)

# Floating point types
for dtype in [np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype.__name__}: min = {info.min}, max = {info.max}, eps = {info.eps}")

int8: min = -128, max = 127
int32: min = -2147483648, max = 2147483647
int64: min = -9223372036854775808, max = 9223372036854775807
------------------------------
float32: min = -3.4028234663852886e+38, max = 3.4028234663852886e+38, eps = 1.1920928955078125e-07
float64: min = -1.7976931348623157e+308, max = 1.7976931348623157e+308, eps = 2.220446049250313e-16


50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [62]:
vec7 = np.random.uniform(0,25,10)
print(vec7)
n = 18
index = (np.abs(vec7 - n)).argmin()
print(index)

[ 2.73897696 13.41479459 18.74337312 21.21740122  8.4339493   4.43212376
 13.90161737 12.80939596  6.31026068 22.34179846]
2


51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [63]:
struc = np.zeros(10, [('position', [('x', 'f4'), 
                                 ('y', 'f4')]),
                   ('color',    [('r', 'u1'), 
                                 ('g', 'u1'), 
                                 ('b', 'u1')])])
print(struc)

[((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0))]


58. Subtract the mean of each row of a matrix (★★☆)

In [66]:
vecMean = np.random.rand(2, 10)
row_means = vecMean.mean(axis=1, keepdims=True)
new = vecMean - row_means
print(new)

[[ 0.36105629 -0.01780899  0.15628231 -0.06801626  0.04170492 -0.15786372
  -0.47230248 -0.1942515   0.30976962  0.04142981]
 [ 0.14937297  0.52229671 -0.09738149 -0.32777599  0.2493089   0.2073979
   0.50696307 -0.43426228 -0.3385488  -0.43737101]]


59. How to sort an array by the nth column? (★★☆)

In [69]:
unsorted = np.random.randint(0, 10, (3, 3))
print("Original:\n", unsorted)
n = 0
indices = unsorted[:, n].argsort()
sorted_arr = unsorted[indices]
print("Original:\n",sorted_arr)

Original:
 [[3 7 3]
 [8 5 7]
 [1 5 8]]
Original:
 [[1 5 8]
 [3 7 3]
 [8 5 7]]


60. How to tell if a given 2D array has null columns? (★★☆)

In [70]:
Z = np.array([
    [1, 0, 3],
    [4, 0, 6],
    [7, 0, 9]
])
null_columns = (~Z.any(axis=0))

# To get a simple True/False if any such column exists:
has_null_column = null_columns.any()

print(f"Column-wise null check: {null_columns}")
print(f"Does it have any null columns? {has_null_column}")

Column-wise null check: [False  True False]
Does it have any null columns? True


62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [71]:
uno = np.array([1,3])
dos = np.array([3,1])
it = np.nditer([uno, dos, None])
for x,y,z in it:
    z[...] = x+y
result = it.operands[2]    
print(result)

[4 4]


69. How to get the diagonal of a dot product? (★★★)

In [73]:
A = np.random.uniform(0, 1, (10, 10))
B = np.random.uniform(0, 1, (10, 10))
result = np.diag(np.dot(A, B))
print(result)

[3.64451514 2.27888388 1.58845389 2.57529044 1.69682996 2.85155782
 3.40860049 2.24345398 1.31887427 2.98654659]


70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [74]:
def interleave_zeros(vector, n_zeros):
    res = np.zeros(len(vector) + (len(vector)-1) * n_zeros)
    res[::n_zeros+1] = vector
    return res
vector = np.array([1, 2, 3, 4, 5])
print(interleave_zeros(vector,3))
    

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


72. How to swap two rows of an array? (★★★)

In [75]:
C = np.arange(15).reshape(5, 3)
print("Original:\n", C)
C[[0, 1]] = C[[1, 0]]

print("\n Swap:\n", C)

Original:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

 Swap:
 [[ 3  4  5]
 [ 0  1  2]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [77]:
uc = np.array([True, False, True], dtype=bool)
negative = ~uc
print(uc)
print(negative)

[ True False  True]
[False  True False]


78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [78]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

def distance_faster(P0,P1,p):
    v = P1- P0 
    v[:,[0,1]] = v[:,[1,0]]
    v[:,1]*=-1 
    norm = np.linalg.norm(v,axis=1)   
    r = P0 - p
    d = np.abs(np.einsum("ij,ij->i",r,v)) / norm 

    return d

print(distance_faster(P0, P1, p))


[17.82452437 12.81419477 15.75941713 17.69800644  9.65533516 14.44452999
  7.94599091  9.37669399  5.44794357 15.93327576]


82. Compute a matrix rank (★★★)

In [87]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
r = a.reshape(3, -1)
print(matrix_rank(a))

1


83. How to find the most frequent value in an array?

In [89]:
vec10 = np.random.randint(0,10,50)
print(vec10)
print(np.bincount(vec10).argmax())

[3 8 1 1 3 9 3 6 8 2 4 7 4 2 1 9 5 5 7 3 9 0 2 7 9 2 6 3 0 6 7 6 8 2 1 3 6
 5 8 2 0 4 7 6 5 3 1 3 6 8]
3


89. How to get the n largest values of an array (★★★)

In [95]:
vect = np.arange(10000)
np.random.shuffle(vect)
n = 5
print (vect[np.argpartition(-vect,n)[:n]])
j = 8
print (vect[np.argpartition(-vect,j)[:j]])

[9999 9997 9998 9996 9995]
[9999 9997 9998 9996 9995 9994 9993 9992]


94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [97]:
uneq = np.random.randint(0, 3, (10, 3))
uneq[0] = [2, 2, 2]
uneq[1] = [1, 2, 3]
iguales = np.all(uneq[:, 1:] == uneq[:, [0]], axis=1)
filas_desiguales = uneq[~iguales]
print(uneq)
print(filas_desiguales)

[[2 2 2]
 [1 2 3]
 [2 2 2]
 [0 1 2]
 [1 0 2]
 [2 1 0]
 [1 2 2]
 [0 1 2]
 [2 1 0]
 [0 2 0]]
[[1 2 3]
 [0 1 2]
 [1 0 2]
 [2 1 0]
 [1 2 2]
 [0 1 2]
 [2 1 0]
 [0 2 0]]
